# Generated by Django 5.1.7 on 2025-03-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        max_length=150,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название привычки", max_length=100, verbose_name="Название привычки"
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True,
                        help_text="Укажите действие, которое представляет собой привычка",
                        null=True,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "lead_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите в какое время планируется выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                ("is_nice_habit", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("once_week", "1 раз в неделю"),
                            ("twice_week", "2 раза в неделю"),
                            ("three_week", "3 раза в неделю"),
                            ("four_week", "4 раза в неделю"),
                            ("five_week", "5 раз в неделю"),
                            ("six_week", "6 раз в неделю"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем Вы хотите себя порадовать?",
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите время на выполнения полезной привычки",
                        null=True,
                        verbose_name="Время на выполнение в секундах",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публиковать привычку")),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
