# Generated by Django 5.1.7 on 2025-03-22 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите время на выполнения полезной привычки",
                null=True,
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Время на выполнение в секундах",
            ),
        ),
    ]
