# Generated by Django 5.1.7 on 2025-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_lead_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date_last_execution",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего выполнения полезной привычки"),
        ),
    ]
