# Generated by Django 5.1.7 on 2025-03-24 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habit_date_last_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Выберите через сколько дней будите выполнять полезную привычку (1-7)",
                validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)],
                verbose_name="Периодичность",
            ),
        ),
    ]
